/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;
import controller.*;
/**
 *
 * @author pichau
 */
public class RefeicaoView extends javax.swing.JFrame {
    private ArrayList<MateriaPrimaModel> ListaMateriaPrima;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RefeicaoView.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public RefeicaoView() {
        initComponents();
        preencherCombo();
        inicializa();
        limparCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        jifRefeicao = new javax.swing.JInternalFrame();
        jpRefeicao = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtRefeicao = new javax.swing.JTable();
        jlCodigo = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jlValor = new javax.swing.JLabel();
        jtxCodigo = new javax.swing.JTextField();
        jtxNome = new javax.swing.JTextField();
        jlMateriaPrima = new javax.swing.JLabel();
        jbAdicionar = new javax.swing.JButton();
        jbPesquisar = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();
        jtxValor = new javax.swing.JTextField();
        jcbMateriaPrima = new javax.swing.JComboBox<>();

        button1.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jifRefeicao.setVisible(true);

        javax.swing.GroupLayout jifRefeicaoLayout = new javax.swing.GroupLayout(jifRefeicao.getContentPane());
        jifRefeicao.getContentPane().setLayout(jifRefeicaoLayout);
        jifRefeicaoLayout.setHorizontalGroup(
            jifRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifRefeicaoLayout.setVerticalGroup(
            jifRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jtRefeicao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Matéria Prima", "Matéria Prima"
            }
        ));
        jScrollPane1.setViewportView(jtRefeicao);

        jlCodigo.setText("Código:");

        jlNome.setText("Nome:");

        jlValor.setText("Valor:");

        jlMateriaPrima.setText("Matéria Prima:");

        jbAdicionar.setText("Adicionar");
        jbAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarActionPerformed(evt);
            }
        });

        jbPesquisar.setText("Pesquisar");

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");

        jbExcluir.setText("Excluir");

        jbFechar.setText("Fechar");
        jbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpRefeicaoLayout = new javax.swing.GroupLayout(jpRefeicao);
        jpRefeicao.setLayout(jpRefeicaoLayout);
        jpRefeicaoLayout.setHorizontalGroup(
            jpRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRefeicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRefeicaoLayout.createSequentialGroup()
                        .addComponent(jbNovo)
                        .addGap(18, 18, 18)
                        .addComponent(jbSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jbEditar)
                        .addGap(18, 18, 18)
                        .addComponent(jbExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jbFechar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpRefeicaoLayout.createSequentialGroup()
                        .addGroup(jpRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCodigo)
                            .addComponent(jlNome)
                            .addComponent(jlValor))
                        .addGap(18, 18, 18)
                        .addGroup(jpRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpRefeicaoLayout.createSequentialGroup()
                                .addComponent(jtxNome)
                                .addGap(206, 206, 206))
                            .addGroup(jpRefeicaoLayout.createSequentialGroup()
                                .addGroup(jpRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpRefeicaoLayout.createSequentialGroup()
                                        .addComponent(jtxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jbPesquisar))
                                    .addComponent(jtxValor, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jpRefeicaoLayout.createSequentialGroup()
                        .addGroup(jpRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpRefeicaoLayout.createSequentialGroup()
                                .addComponent(jlMateriaPrima)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jbAdicionar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jpRefeicaoLayout.setVerticalGroup(
            jpRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRefeicaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigo)
                    .addComponent(jtxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPesquisar))
                .addGap(18, 18, 18)
                .addGroup(jpRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlValor)
                    .addComponent(jtxValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAdicionar)
                    .addGroup(jpRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlMateriaPrima)
                        .addComponent(jcbMateriaPrima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpRefeicaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNovo)
                    .addComponent(jbSalvar)
                    .addComponent(jbEditar)
                    .addComponent(jbExcluir)
                    .addComponent(jbFechar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jpRefeicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jifRefeicao))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jifRefeicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpRefeicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        jbPesquisar.setEnabled(false);
        jbNovo.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbSalvar.setEnabled(true);
        jtxCodigo.setEditable(false);
        jtxNome.setEditable(true);
        jtxValor.setEditable(true);
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        RefeicaoModel refeicao = new RefeicaoModel();
        refeicao.setNome(jtxNome.getText());
        refeicao.setValor(Float.parseFloat(jtxValor.getText()));
        
        RefeicaoController controller = new RefeicaoController();
        controller.inserir(refeicao);
        int codigoRefeicao = controller.selecionarUltimoId();
        
        IngredientesController controllerIngredientes = new IngredientesController();
        for(int i=0; i< jtRefeicao.getRowCount();i++){
            IngredientesModel IM = new IngredientesModel();
            IM.getRefeicao().setIdRefeicao(codigoRefeicao);
            IM.getMateriaPrima().setIdMateriaPrima(Integer.parseInt(jtRefeicao.getValueAt(i, 0).toString()));
            controllerIngredientes.inserir(IM);
            }
        
        JOptionPane.showMessageDialog(this, "Refeição cadastrada com sucesso!");
        preencherCombo();
        inicializa();
        limparCampos();
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jbFecharActionPerformed

    private void jbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarActionPerformed
        String prod = (String)jcbMateriaPrima.getSelectedItem();
            int idMateriaPrima = 0;
            for(int i=0; i<ListaMateriaPrima.size();i++){
                if(prod.equals(ListaMateriaPrima.get(i).getNome())){
                    idMateriaPrima = ListaMateriaPrima.get(i).getIdMateriaPrima();
                    break;
                }
            }
          
        //String quantidade = jtxQuantidade.getText();
        DefaultTableModel modelo = (DefaultTableModel) jtRefeicao.getModel();
        modelo.addRow(new String[]{String.valueOf(idMateriaPrima), prod});
        //jtxQuantidade.setText("");
        jcbMateriaPrima.setSelectedIndex(0);
    }//GEN-LAST:event_jbAdicionarActionPerformed

    private void preencherCombo(){
        MateriaPrimaController controller = new MateriaPrimaController();
         ListaMateriaPrima = controller.selecionarTodos();
        for(MateriaPrimaModel p: ListaMateriaPrima)
            jcbMateriaPrima.addItem(p.getNome());
    }
    private void inicializa(){
        jtxNome.setEditable(false);
        jtxValor.setEditable(false);
        jbSalvar.setEnabled(false);
        jbEditar.setEnabled(false);
        jbExcluir.setEnabled(false);
        jbPesquisar.setEnabled(true);
        jbNovo.setEnabled(true);
    }
    private void limparCampos(){
        jtxNome.setText("");
        jtxValor.setText("");
    }

    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAdicionar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox<String> jcbMateriaPrima;
    private javax.swing.JInternalFrame jifRefeicao;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlMateriaPrima;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlValor;
    private javax.swing.JPanel jpRefeicao;
    private javax.swing.JTable jtRefeicao;
    private javax.swing.JTextField jtxCodigo;
    private javax.swing.JTextField jtxNome;
    private javax.swing.JTextField jtxValor;
    // End of variables declaration//GEN-END:variables
}